apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: candlestick-ingress
  labels:
    name: candlestick-ingress
  namespace: _{_NAMESPACE_}_
spec:
  rules:
  - host: candlestick-app-_{_NAMESPACE_}_.myapp.ito
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: candlestick-frontend-service
            port:
              number: 80