name: Candlestick Frontend Pipeline

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
    unit_test_job:
        name: Unit Test
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: '24.11'

            - name: Cache NPM dependencies
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    ${{ runner.os }}-node-
            
            - name: Install Dependencies
              run: npm install

            - name: Unit Test
              run: npm test

            - name: Archive Test Results
              uses: actions/upload-artifact@v4
              with:
                name: Event Test Result
                path: artifacts/event-test.xml
                retention-days: 5
    code_coverage_job:
        name: Code Coverage
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: '24.11'

            - name: Cache NPM dependencies
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    ${{ runner.os }}-node-

            - name: Install Dependencies
              run: npm install

            - name: Run Code Coverage
              run: npm run coverage

            - name: Archive Code Coverage Results
              uses: actions/upload-artifact@v4
              with:
                name: Code Coverage Result
                path: coverage
                retention-days: 5
    verify_unit_test_job:
        name: Verify Unit Test
        needs: unit_test_job
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Download Test Results
              uses: actions/download-artifact@v4
              with:
                name: Event Test Result

            - name: Simple Display Results
              run: |
                  cat event-test.xml
    build_image_job:
        name: Docker Containerization
        needs: unit_test_job
        #if: github.ref == 'refs/head/main'
        runs-on: self-hosted
        steps:
            - name: Docker Login
              uses: docker/login-action@v2.2.0
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD}}

            - name: Docker Build
              uses: docker/build-push-action@v4
              with:
                context: .
                push: false
                tags: ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

            - name: Docker Image Testing
              run: |
                  docker run --name frontend-app -itd \
                      -p 3000:3000 \
                      ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

                  sleep 30s
                  curl http://localhost:3000/

            #- name: Docker Build
            #  run: sudo docker build -t ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest .

            #- name: Docker Login
            #  run: sudo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD}}

            #- name: Docker Publish
            #  run: sudo docker push ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

            #- name: Docker Logout
            #  run: sudo docker logout https://docker.io
    test_image_job:
        name: Test Docker Image
        if: github.ref == 'refs/head/main'
        needs: build_image_job
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5
                  
            - name: Run Docker image
              run: | 
                  sudo docker run -itd -p 3000:3000 --name frontend-app ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
                  sleep 30s

            - name: Test Docker Image
              run: curl http://localhost:3000/test

            - name: Clean Docker Deployments
              run: |
                  sudo docker stop frontend-app && sudo docker rm frontend-app
    deploy_image_job:
        name: Deploy Docker Image
        if: github.ref == 'refs/head/main'
        needs: test_image_job
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              
            - name: Deploy Application
              run: |
                  cat README.md
