name: Candlestick Frontend Pipeline

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
    unit_test_job:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup NodeJS Version - 
              uses: actions/setup-node@v4
              with:
                node-version: '24.11'

            - name: Install Dependencies
              uses: actions/checkout@v5

            - name: Unit Test
              uses: npm test
    build_job:
        if: github.ref == 'refs/head/main'
        runs-on: self-hosted
        steps:
            - name: Docker Build
              run: sudo docker build -t ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest .

            - name: Docker Login
              run: sudo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD}}

            - name: Docker Publish
              run: sudo docker push ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

            - name: Docker Logout
              run: sudo docker logout https://docker.io
    test_job:
        if: github.ref == 'refs/head/main'
        needs: build_job
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5
                  
            - name: Run Docker image
              run: | 
                  sudo docker run -itd -p 3000:3000 --name frontend-app ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
                  sleep 30s

            - name: Test Docker Image
              run: curl http://localhost:3000/test

            - name: Clean Docker Deployments
              run: |
                  sudo docker stop frontend-app && sudo docker rm frontend-app
    deploy_job:
        if: github.ref == 'refs/head/main'
        needs: test_job
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              
            - name: Deploy Application
              run: |
                  cat README.md
